version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Install Flutter
      - wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.10.0-stable.tar.xz
      - tar xf flutter_linux_3.10.0-stable.tar.xz
      - export PATH="$PATH:`pwd`/flutter/bin"
      - flutter doctor
      - flutter precache
      - flutter config --enable-web
      - flutter pub get
  build:
    commands:
      - flutter build web
artifacts:
  files:
    - '**/*'
  base-directory: build/web
